### ISSUE TITLE
API changes

### ISSUE THREAD

**Issue by DonaldTsang** [Atulin/Chryssibooru#14]
See https://github.com/Sibusten/derpibooru-downloader/issues/30 for API and web changes.

**Comment by Atulin** [comment]
Ah, the switch to Philomena went live? I'll get right to replacing the API, thankfully I do already have everything prepared, just gotta swap the API provicer class and push a new release.

**Comment by Atulin** [comment]
Fixed, updated version [has been released](https://github.com/Atulin/Chryssibooru/releases/tag/v1.6.0).

Closing.
